#!/usr/bin/env python3
"""
Dependency Analyzer - Critical Path Method using NetworkX

PURPOSE:
    Analyzes task dependencies to find:
    - Critical path (longest sequence of dependent tasks)
    - Parallel execution opportunities
    - Bottleneck tasks
    - Circular dependencies (errors)

INPUTS:
    - JSON file with task definitions (structure documented below)

OUTPUTS:
    - JSON report with optimization recommendations

DEPENDENCIES:
    - networkx: Graph algorithms and network analysis
    - json: JSON parsing
    - sys: Command-line arguments

USAGE:
    python 1_dependency_analyzer.py <tasks.json>

TESTING:
    Run with test_tasks.json to validate functionality

AI REVIEW NOTES:
    - All functions have type hints for clarity
    - Error handling for cycles and invalid graphs
    - Comments explain WHY not just WHAT
    - Follows Python PEP 8 style guidelines

AUTHOR: Generated by Claude Code strategic-planner skill
VERSION: 1.0.0
"""

import json
import sys
from typing import Dict, List, Tuple, Any

# Check if networkx is available, fail gracefully if not
try:
    import networkx as nx
except ImportError:
    print("ERROR: networkx library not found. Install with: pip install networkx")
    sys.exit(1)


def load_tasks(tasks_json_path: str) -> Dict[str, Any]:
    """
    Load tasks from JSON file.

    Args:
        tasks_json_path: Path to JSON file containing tasks

    Returns:
        Dictionary mapping task IDs to task data

    Raises:
        FileNotFoundError: If JSON file doesn't exist
        json.JSONDecodeError: If JSON is invalid

    Expected JSON structure:
    {
        "task_1.1": {
            "name": "Task name",
            "duration_minutes": 5,
            "depends_on": ["task_0.1"],  # List of task IDs this depends on
            "files": ["path/to/file.php"],
            "risk": "low|medium|high"
        }
    }
    """
    try:
        with open(tasks_json_path, 'r', encoding='utf-8') as f:
            tasks = json.load(f)

        # Validate structure
        if not isinstance(tasks, dict):
            raise ValueError("Tasks must be a dictionary")

        return tasks

    except FileNotFoundError:
        print(f"ERROR: File not found: {tasks_json_path}")
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"ERROR: Invalid JSON: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"ERROR: Failed to load tasks: {e}")
        sys.exit(1)


def build_dependency_graph(tasks: Dict[str, Any]) -> nx.DiGraph:
    """
    Build directed graph from task dependencies.

    Graph structure:
    - Nodes: Tasks (with attributes: name, duration, files, risk)
    - Edges: Dependencies (task A → task B means B depends on A)

    Args:
        tasks: Dictionary of task definitions

    Returns:
        NetworkX directed graph representing task dependencies

    AI REVIEW NOTE:
        DiGraph = Directed Graph (one-way dependencies)
        If task B depends on task A, edge goes A → B
    """
    # Create empty directed graph
    G = nx.DiGraph()

    # Add each task as a node with its attributes
    for task_id, task_data in tasks.items():
        G.add_node(
            task_id,
            name=task_data.get('name', 'Unnamed Task'),
            duration=task_data.get('duration_minutes', 5),  # Default 5 min if missing
            files=task_data.get('files', []),
            risk=task_data.get('risk', 'low')
        )

    # Add edges for dependencies
    # If task B depends on [A], create edge A → B
    for task_id, task_data in tasks.items():
        dependencies = task_data.get('depends_on', [])

        # Validate dependencies exist
        for dependency_id in dependencies:
            if dependency_id not in tasks:
                print(f"WARNING: Task {task_id} depends on non-existent task {dependency_id}")
                continue

            # Add edge: dependency → task (dependency must complete before task)
            G.add_edge(dependency_id, task_id)

    return G


def detect_cycles(G: nx.DiGraph) -> List[List[str]]:
    """
    Detect circular dependencies in task graph.

    Circular dependency = Task A depends on B, B depends on C, C depends on A
    This is an error because tasks can never start (waiting on each other)

    Args:
        G: Directed graph of tasks

    Returns:
        List of cycles, where each cycle is a list of task IDs
        Empty list if no cycles

    Example cycle:
        [['task_1', 'task_2', 'task_3']]
        means: task_1 → task_2 → task_3 → task_1 (circular!)
    """
    try:
        # NetworkX provides built-in cycle detection
        cycles = list(nx.simple_cycles(G))
        return cycles
    except Exception as e:
        print(f"ERROR: Failed to detect cycles: {e}")
        return []


def calculate_critical_path(G: nx.DiGraph) -> Tuple[List[str], int]:
    """
    Calculate critical path using longest path algorithm.

    Critical path = Longest sequence of dependent tasks
    Determines minimum project duration
    Tasks on critical path have zero slack (any delay delays whole project)

    Args:
        G: Directed graph of tasks (must be acyclic!)

    Returns:
        Tuple of (critical_path_tasks, total_duration_minutes)

    Raises:
        ValueError: If graph has cycles

    ALGORITHM EXPLANATION (for AI review):
    1. Forward pass: Calculate earliest start time for each task
       - Root tasks start at time 0
       - Other tasks start when all dependencies complete

    2. Backward pass: Calculate latest start time for each task
       - Work backward from project end
       - Latest time that doesn't delay project

    3. Calculate slack (float): Latest - Earliest
       - Zero slack = critical path
       - Positive slack = can be delayed without affecting project

    COMPLEXITY: O(V + E) where V=tasks, E=dependencies
    """
    # Verify graph is acyclic (required for critical path)
    if not nx.is_directed_acyclic_graph(G):
        raise ValueError("Graph has cycles - cannot calculate critical path. Fix circular dependencies first.")

    # STEP 1: Forward pass - Calculate earliest start times
    earliest_start = {}

    # Process tasks in topological order (dependencies before dependents)
    for node in nx.topological_sort(G):
        # Get all tasks that must complete before this one
        predecessors = list(G.predecessors(node))

        if not predecessors:
            # Root task - can start immediately
            earliest_start[node] = 0
        else:
            # Start when all dependencies complete
            # Max = latest completion time of any dependency
            earliest_start[node] = max(
                earliest_start[pred] + G.nodes[pred]['duration']
                for pred in predecessors
            )

    # STEP 2: Calculate total project duration
    # Maximum of (earliest_start + duration) for all tasks
    project_duration = max(
        earliest_start[node] + G.nodes[node]['duration']
        for node in G.nodes()
    )

    # STEP 3: Backward pass - Calculate latest start times
    latest_start = {}

    # Process in reverse topological order (dependents before dependencies)
    for node in reversed(list(nx.topological_sort(G))):
        # Get all tasks that depend on this one
        successors = list(G.successors(node))

        if not successors:
            # Leaf task - must finish by project end
            latest_start[node] = project_duration - G.nodes[node]['duration']
        else:
            # Must finish before earliest dependent starts
            # Min = earliest start time of any dependent
            latest_start[node] = min(
                latest_start[succ] - G.nodes[node]['duration']
                for succ in successors
            )

    # STEP 4: Calculate slack (float) for each task
    slack = {
        node: latest_start[node] - earliest_start[node]
        for node in G.nodes()
    }

    # STEP 5: Critical path = all tasks with zero slack
    critical_path = [node for node, slack_time in slack.items() if slack_time == 0]

    # Sort critical path by execution order (earliest start time)
    critical_path.sort(key=lambda n: earliest_start[n])

    return critical_path, project_duration


def find_parallelizable_tasks(G: nx.DiGraph) -> List[List[str]]:
    """
    Find tasks that can be executed in parallel.

    Tasks can run in parallel if:
    - They don't depend on each other
    - They're at the same "level" (same distance from start)

    Returns list of groups where each group can run simultaneously.

    Args:
        G: Directed graph of tasks

    Returns:
        List of parallel groups, where each group is a list of task IDs

    Example:
        [
            ["task_1.1"],              # Phase 1: Only 1 task
            ["task_2.1", "task_2.2"],  # Phase 2: 2 tasks in parallel
            ["task_3.1"]               # Phase 3: Only 1 task
        ]

    ALGORITHM:
    1. Assign each task a "level" (distance from root)
    2. Group tasks by level
    3. Tasks in same level can run in parallel

    AI REVIEW NOTE:
        This is a conservative approach - it groups by level.
        Could be optimized further by checking file conflicts,
        but safer to be conservative.
    """
    # Calculate level (depth) for each task
    levels = {}

    for node in nx.topological_sort(G):
        predecessors = list(G.predecessors(node))

        if not predecessors:
            # Root task - level 0
            levels[node] = 0
        else:
            # Level = max level of dependencies + 1
            levels[node] = max(levels[pred] for pred in predecessors) + 1

    # Group tasks by level
    parallel_groups = {}
    for node, level in levels.items():
        if level not in parallel_groups:
            parallel_groups[level] = []
        parallel_groups[level].append(node)

    # Return as sorted list of groups
    # Sort by level to maintain execution order
    return [parallel_groups[level] for level in sorted(parallel_groups.keys())]


def calculate_bottlenecks(G: nx.DiGraph) -> List[Tuple[str, float]]:
    """
    Find bottleneck tasks using betweenness centrality.

    Betweenness centrality = How many paths go through this task
    High centrality = bottleneck (many tasks wait on this)

    Args:
        G: Directed graph of tasks

    Returns:
        List of (task_id, centrality_score) tuples, sorted by score
        Higher score = bigger bottleneck

    WHY THIS MATTERS:
        - Bottleneck tasks should be prioritized
        - Consider allocating more resources to bottlenecks
        - Reducing bottleneck duration has max impact on project time

    AI REVIEW NOTE:
        Centrality range: 0.0 (no paths through it) to 1.0 (all paths through it)
    """
    try:
        # Calculate betweenness centrality for all nodes
        centrality = nx.betweenness_centrality(G)

        # Sort by centrality (highest first)
        bottlenecks = sorted(
            centrality.items(),
            key=lambda x: x[1],
            reverse=True
        )

        # Return top 5 bottlenecks
        return bottlenecks[:5]

    except Exception as e:
        print(f"WARNING: Failed to calculate bottlenecks: {e}")
        return []


def generate_optimization_report(G: nx.DiGraph) -> Dict[str, Any]:
    """
    Generate comprehensive optimization report.

    Combines all analysis into single report for Claude to read.

    Args:
        G: Directed graph of tasks

    Returns:
        Dictionary with optimization recommendations

    REPORT STRUCTURE:
    {
        "critical_path": ["task_1", "task_2"],  # Tasks on longest path
        "project_duration_minutes": 42,         # Min time to complete
        "parallel_groups": [[tasks], [tasks]],  # Parallelization opportunities
        "bottlenecks": [{"task": "x", "centrality": 0.5}],
        "has_cycles": false,                    # Circular dependency check
        "total_tasks": 10,
        "total_dependencies": 12
    }
    """
    try:
        # Check for cycles first (fatal error)
        cycles = detect_cycles(G)
        if cycles:
            return {
                'error': 'CIRCULAR_DEPENDENCIES',
                'has_cycles': True,
                'cycles': cycles,
                'message': 'Fix circular dependencies before proceeding',
                'total_tasks': len(G.nodes()),
                'total_dependencies': len(G.edges())
            }

        # Calculate critical path
        critical_path, duration = calculate_critical_path(G)

        # Find parallelizable tasks
        parallel_groups = find_parallelizable_tasks(G)

        # Identify bottlenecks
        bottlenecks = calculate_bottlenecks(G)

        # Build report
        return {
            'status': 'SUCCESS',
            'critical_path': critical_path,
            'project_duration_minutes': duration,
            'parallel_groups': parallel_groups,
            'bottlenecks': [
                {'task': task_id, 'centrality': score}
                for task_id, score in bottlenecks
            ],
            'has_cycles': False,
            'cycles': [],
            'total_tasks': len(G.nodes()),
            'total_dependencies': len(G.edges()),
            'optimization_potential': {
                'sequential_duration': sum(G.nodes[n]['duration'] for n in G.nodes()),
                'parallel_duration': duration,
                'time_saved': sum(G.nodes[n]['duration'] for n in G.nodes()) - duration,
                'efficiency_gain_percent': round(
                    (1 - duration / sum(G.nodes[n]['duration'] for n in G.nodes())) * 100,
                    1
                ) if sum(G.nodes[n]['duration'] for n in G.nodes()) > 0 else 0
            }
        }

    except Exception as e:
        return {
            'error': 'ANALYSIS_FAILED',
            'message': str(e),
            'total_tasks': len(G.nodes()),
            'total_dependencies': len(G.edges())
        }


def main():
    """
    Main execution function.

    Process:
    1. Load tasks from JSON
    2. Build dependency graph
    3. Analyze and optimize
    4. Output JSON report

    EXIT CODES:
        0 = Success
        1 = Error (invalid input, cycles, etc.)
    """
    # Check command-line arguments
    if len(sys.argv) < 2:
        print("Usage: python 1_dependency_analyzer.py <tasks.json>")
        print("\nExample:")
        print("  python 1_dependency_analyzer.py temp/test_tasks.json")
        sys.exit(1)

    tasks_file = sys.argv[1]

    # Load and validate tasks
    tasks = load_tasks(tasks_file)

    # Build dependency graph
    G = build_dependency_graph(tasks)

    # Generate optimization report
    report = generate_optimization_report(G)

    # Output as JSON for Claude to parse
    print(json.dumps(report, indent=2))

    # Exit with appropriate code
    if 'error' in report:
        sys.exit(1)
    else:
        sys.exit(0)


# Entry point
if __name__ == '__main__':
    main()
