#!/usr/bin/env python3
"""
Atomicity Validator - Validates SMART-E Atomic Task Rules

PURPOSE:
    Validates tasks against SMART-E criteria and atomicity rules:
    - S: Specific (exact changes defined)
    - M: Measurable (clear success criteria)
    - A: Achievable (no blockers)
    - R: Relevant (contributes to goal)
    - T: Testable (verification command)
    - E: Executable (can start immediately or after dependencies)

    Plus 5 atomicity rules:
    1. ≤3 files modified
    2. <30 minutes duration
    3. Binary done state (not "partially done")
    4. Independently verifiable
    5. Single responsibility

INPUTS:
    - JSON file with task definitions

OUTPUTS:
    - Validation report with pass/warn/fail for each rule
    - Overall verdict: PASS or FAIL
    - Specific recommendations for fixing violations

DEPENDENCIES:
    - json: JSON parsing
    - sys: Command-line arguments
    - dataclasses: Structured validation results

USAGE:
    python 2_atomicity_validator.py <tasks.json>

EXIT CODES:
    0 = All tasks pass validation
    1 = One or more tasks fail validation

AI REVIEW NOTES:
    - Comprehensive validation with clear severity levels
    - Each rule has dedicated validator method
    - Detailed error messages for debugging
    - No external dependencies (pure Python)

AUTHOR: Generated by Claude Code strategic-planner skill
VERSION: 1.0.0
"""

import json
import sys
from dataclasses import dataclass
from typing import Dict, List, Any, Optional


@dataclass
class ValidationResult:
    """
    Represents validation result for a single rule.

    Attributes:
        task_id: Identifier of the task being validated
        rule: Name of the rule being checked
        status: 'pass', 'warn', or 'fail'
        message: Human-readable description of the result
        severity: 1 (low), 2 (medium), or 3 (high)
    """
    task_id: str
    rule: str
    status: str  # 'pass', 'warn', 'fail'
    message: str
    severity: int  # 1=low, 2=medium, 3=high


class AtomicityValidator:
    """
    Validates tasks against SMART-E and atomicity criteria.

    Configuration:
        max_files: Maximum files that can be modified in one task (default: 3)
        max_minutes: Maximum duration for one task (default: 30)

    Usage:
        validator = AtomicityValidator(max_files=3, max_minutes=30)
        report = validator.validate_all(tasks)
    """

    def __init__(self, max_files: int = 3, max_minutes: int = 30):
        """
        Initialize validator with configurable limits.

        Args:
            max_files: Maximum files per task (atomicity rule 1)
            max_minutes: Maximum duration per task (atomicity rule 2)
        """
        self.max_files = max_files
        self.max_minutes = max_minutes
        self.results: List[ValidationResult] = []

    def validate_task(self, task_id: str, task: Dict[str, Any]) -> List[ValidationResult]:
        """
        Validate single task against all rules.

        Args:
            task_id: Unique identifier for the task
            task: Dictionary containing task data

        Returns:
            List of ValidationResult objects (one per rule checked)

        Process:
            1. Validate atomicity rules (5 rules)
            2. Validate SMART-E criteria (6 criteria)
            3. Return all results (filter out None values)
        """
        results = []

        # ATOMICITY RULES (5 rules)
        results.append(self._validate_file_count(task_id, task))
        results.append(self._validate_time_estimate(task_id, task))
        results.append(self._validate_done_state(task_id, task))
        results.append(self._validate_verification(task_id, task))
        results.append(self._validate_single_responsibility(task_id, task))

        # SMART-E CRITERIA (6 criteria)
        results.extend(self._validate_smart_e(task_id, task))

        # Filter out None results (optional validations that may not apply)
        return [r for r in results if r is not None]

    def _validate_file_count(self, task_id: str, task: Dict) -> ValidationResult:
        """
        ATOMICITY RULE 1: Validate ≤3 files modified.

        Why this matters:
            - More files = more complexity
            - More files = higher chance of conflicts
            - More files = harder to verify

        Thresholds:
            - 0-1 files: PASS (ideal)
            - 2-3 files: WARN (acceptable but consider splitting)
            - 4+ files: FAIL (must split into multiple tasks)

        Special case:
            - 0 files: Database operations, bash commands (PASS)
        """
        files = task.get('files', [])
        count = len(files)

        if count == 0:
            # Database ops, bash commands, etc. - no files modified
            return ValidationResult(
                task_id, 'file_count', 'pass',
                f"No files modified (database/command operation)", 1
            )
        elif count == 1:
            # Ideal case - atomic modification
            return ValidationResult(
                task_id, 'file_count', 'pass',
                f"✅ Ideal: 1 file modified", 1
            )
        elif count <= self.max_files:
            # Acceptable but not ideal
            return ValidationResult(
                task_id, 'file_count', 'warn',
                f"⚠️ Warning: {count} files (acceptable but consider splitting)", 2
            )
        else:
            # Too many files - must split
            return ValidationResult(
                task_id, 'file_count', 'fail',
                f"❌ FAIL: {count} files exceeds limit of {self.max_files}. MUST SPLIT.", 3
            )

    def _validate_time_estimate(self, task_id: str, task: Dict) -> ValidationResult:
        """
        ATOMICITY RULE 2: Validate <30 minutes duration.

        Why this matters:
            - Long tasks are hard to estimate
            - Long tasks increase risk
            - Long tasks are not truly atomic

        Thresholds:
            - <10 minutes: PASS (ideal)
            - 10-30 minutes: WARN (acceptable)
            - >30 minutes: FAIL (must split)
        """
        duration = task.get('duration_minutes')

        if duration is None:
            # Missing estimate is a critical error
            return ValidationResult(
                task_id, 'time_estimate', 'fail',
                "❌ Missing duration estimate", 3
            )

        if duration < 10:
            # Quick task - ideal
            return ValidationResult(
                task_id, 'time_estimate', 'pass',
                f"✅ Ideal: {duration} minutes", 1
            )
        elif duration <= self.max_minutes:
            # Acceptable but getting long
            return ValidationResult(
                task_id, 'time_estimate', 'warn',
                f"⚠️ Acceptable: {duration} minutes (close to limit)", 2
            )
        else:
            # Too long - must split
            return ValidationResult(
                task_id, 'time_estimate', 'fail',
                f"❌ FAIL: {duration} minutes exceeds {self.max_minutes}. MUST SPLIT.", 3
            )

    def _validate_done_state(self, task_id: str, task: Dict) -> ValidationResult:
        """
        ATOMICITY RULE 3: Validate binary completion criteria.

        Binary = Task is either DONE or NOT DONE (no in-between)

        Good criteria:
            - "File exists at path/to/file.php"
            - "Tests pass: 4/4"
            - "PHPStan returns 0 errors"

        Bad (fuzzy) criteria:
            - "Mostly implemented"
            - "Approximately 80% complete"
            - "Almost done"

        Detection:
            Scan for fuzzy words: mostly, partially, almost, approximately, around
        """
        dod = task.get('definition_of_done', [])

        if not dod:
            return ValidationResult(
                task_id, 'done_state', 'fail',
                "❌ Missing Definition of Done", 3
            )

        # Check for fuzzy language (indicates non-binary criteria)
        fuzzy_words = ['mostly', 'partially', 'almost', 'approximately', 'around', 'about']
        fuzzy_found = []

        for criterion in dod:
            criterion_lower = str(criterion).lower()
            for word in fuzzy_words:
                if word in criterion_lower:
                    fuzzy_found.append(word)

        if fuzzy_found:
            # Found fuzzy language - criteria not binary
            return ValidationResult(
                task_id, 'done_state', 'fail',
                f"❌ Fuzzy criteria found: {', '.join(set(fuzzy_found))}. Use binary criteria.", 3
            )

        # All criteria appear binary
        return ValidationResult(
            task_id, 'done_state', 'pass',
            f"✅ Binary done state ({len(dod)} criteria)", 1
        )

    def _validate_verification(self, task_id: str, task: Dict) -> ValidationResult:
        """
        ATOMICITY RULE 4: Validate independent verification.

        Independent = Can verify task completion without running other tasks

        Good verification:
            - "phpstan analyse File.php" (runs independently)
            - "test -f path/to/file.php" (checks file exists)
            - "vendor/bin/phpunit TestFile.php" (runs test)

        Bad verification:
            - "After task X completes, check Y" (depends on other task)
            - "Requires task Z to verify" (not independent)

        Why this matters:
            - Can verify each task in isolation
            - Don't need to complete whole project to check one task
            - Enables incremental validation
        """
        verification = task.get('verification_command')

        if not verification:
            return ValidationResult(
                task_id, 'verification', 'fail',
                "❌ Missing verification command", 3
            )

        # Check if verification depends on other tasks
        # Look for phrases indicating dependencies
        dependency_patterns = [
            'after task', 'requires task', 'depends on',
            'when task', 'once task', 'wait for'
        ]

        verification_lower = str(verification).lower()
        has_dependency = any(
            pattern in verification_lower
            for pattern in dependency_patterns
        )

        if has_dependency:
            return ValidationResult(
                task_id, 'verification', 'fail',
                "❌ Verification depends on other tasks - not independently verifiable", 3
            )

        # Verification appears independent
        return ValidationResult(
            task_id, 'verification', 'pass',
            "✅ Independently verifiable", 1
        )

    def _validate_single_responsibility(self, task_id: str, task: Dict) -> ValidationResult:
        """
        ATOMICITY RULE 5: Validate single responsibility.

        Single responsibility = Task does ONE thing only

        Good task names:
            - "Create CookieFlavor value object"
            - "Run migration"
            - "Update Cookie entity constructor"

        Bad task names:
            - "Create value object and update entity and add tests" (3 things!)
            - "Update constructor, then add getter, also modify factory" (3 things!)

        Detection:
            1. Check for conjunctions (and, then, also)
            2. Count action verbs (should be exactly 1)

        Why this matters:
            - Easy to understand what task does
            - Easy to estimate time
            - Easy to verify completion
            - If task fails, know exactly what failed
        """
        name = task.get('name', '')

        # Check for conjunctions indicating multiple actions
        multi_action_words = [' and ', ' then ', ' also ', ', and ', '; ']
        has_multiple = any(word in name.lower() for word in multi_action_words)

        if has_multiple:
            return ValidationResult(
                task_id, 'single_responsibility', 'fail',
                f"❌ Multiple actions detected in: '{name}'. MUST SPLIT.", 3
            )

        # Check for action verb count
        action_verbs = [
            'create', 'update', 'delete', 'add', 'remove',
            'modify', 'run', 'test', 'validate', 'refactor',
            'fix', 'implement', 'build', 'generate', 'write'
        ]

        name_lower = name.lower()
        verb_count = sum(1 for verb in action_verbs if verb in name_lower)

        if verb_count > 1:
            # Multiple verbs - probably multiple actions
            return ValidationResult(
                task_id, 'single_responsibility', 'warn',
                f"⚠️ Multiple verbs ({verb_count}) detected. Consider splitting.", 2
            )
        elif verb_count == 1:
            # Exactly one verb - good!
            return ValidationResult(
                task_id, 'single_responsibility', 'pass',
                "✅ Single responsibility", 1
            )
        else:
            # No clear action verb - unclear what task does
            return ValidationResult(
                task_id, 'single_responsibility', 'warn',
                "⚠️ No clear action verb in task name", 2
            )

    def _validate_smart_e(self, task_id: str, task: Dict) -> List[ValidationResult]:
        """
        Validate SMART-E criteria.

        SMART-E breakdown:
            S - Specific: Exact changes defined
            M - Measurable: Clear success criteria
            A - Achievable: No blockers preventing start
            R - Relevant: Contributes to larger goal
            T - Testable: Verification command exists
            E - Executable: Can start now or after deps

        Returns:
            List of ValidationResult objects (one per failed criterion)
            Empty list if all pass

        Note:
            Only returns results for failures/warnings
            Passing criteria are not reported (reduce noise)
        """
        results = []

        # S - Specific
        if not task.get('specific_changes'):
            results.append(ValidationResult(
                task_id, 'smart_specific', 'fail',
                "❌ Missing 'specific_changes' (what exactly to do)", 3
            ))

        # M - Measurable
        if not task.get('success_criteria'):
            results.append(ValidationResult(
                task_id, 'smart_measurable', 'fail',
                "❌ Missing 'success_criteria' (how to measure success)", 3
            ))

        # A - Achievable
        blockers = task.get('blockers', [])
        # Check for actual blockers (not just 'none' placeholder)
        if blockers and blockers != ['none'] and blockers != []:
            results.append(ValidationResult(
                task_id, 'smart_achievable', 'warn',
                f"⚠️ Has blockers: {', '.join(blockers)}", 2
            ))

        # R - Relevant
        if not task.get('contributes_to'):
            results.append(ValidationResult(
                task_id, 'smart_relevant', 'warn',
                "⚠️ Missing 'contributes_to' (why this task matters)", 2
            ))

        # T - Testable (already checked in _validate_verification)
        # Skip to avoid duplicate

        # E - Executable
        can_start = task.get('can_start_immediately', False)
        depends_on = task.get('depends_on', [])

        if not can_start and not depends_on:
            # Can't start immediately but no dependencies listed
            # This is inconsistent
            results.append(ValidationResult(
                task_id, 'smart_executable', 'fail',
                "❌ Cannot start immediately but has no dependencies listed", 3
            ))

        return results

    def validate_all(self, tasks: Dict[str, Dict]) -> Dict[str, Any]:
        """
        Validate all tasks and generate comprehensive report.

        Args:
            tasks: Dictionary mapping task IDs to task data

        Returns:
            Report dictionary with:
                - Summary statistics
                - Detailed failures and warnings
                - Overall verdict (PASS/FAIL)
                - Recommendations

        Process:
            1. Validate each task
            2. Collect all results
            3. Categorize by status (pass/warn/fail)
            4. Generate summary
            5. Determine verdict
        """
        all_results = []

        # Validate each task
        for task_id, task_data in tasks.items():
            results = self.validate_task(task_id, task_data)
            all_results.extend(results)

        # Categorize results
        failures = [r for r in all_results if r.status == 'fail']
        warnings = [r for r in all_results if r.status == 'warn']
        passes = [r for r in all_results if r.status == 'pass']

        # Calculate pass rate
        total_checks = len(all_results)
        pass_rate = (len(passes) / total_checks * 100) if total_checks > 0 else 0

        # Overall verdict
        verdict = 'PASS' if len(failures) == 0 else 'FAIL'

        # Generate recommendation
        if len(failures) == 0:
            if len(warnings) == 0:
                recommendation = '✅ All tasks are atomic and well-defined'
            else:
                recommendation = f'⚠️ {len(warnings)} warnings found but no critical issues'
        else:
            recommendation = f'❌ Fix {len(failures)} critical issues before proceeding'

        # Build report
        return {
            'total_tasks': len(tasks),
            'total_checks': total_checks,
            'failures': len(failures),
            'warnings': len(warnings),
            'passes': len(passes),
            'pass_rate': round(pass_rate, 1),
            'details': {
                'failures': [
                    {
                        'task': r.task_id,
                        'rule': r.rule,
                        'message': r.message,
                        'severity': r.severity
                    }
                    for r in failures
                ],
                'warnings': [
                    {
                        'task': r.task_id,
                        'rule': r.rule,
                        'message': r.message
                    }
                    for r in warnings
                ]
            },
            'verdict': verdict,
            'recommendation': recommendation
        }


def main():
    """
    Main execution function.

    Process:
        1. Parse command-line arguments
        2. Load tasks from JSON
        3. Run validation
        4. Output report as JSON
        5. Exit with appropriate code

    Exit codes:
        0 = All validations passed
        1 = One or more validations failed
    """
    # Check arguments
    if len(sys.argv) < 2:
        print("Usage: python 2_atomicity_validator.py <tasks.json>")
        print("\nExample:")
        print("  python 2_atomicity_validator.py temp/test_tasks.json")
        sys.exit(1)

    tasks_file = sys.argv[1]

    # Load tasks
    try:
        with open(tasks_file, 'r', encoding='utf-8') as f:
            tasks = json.load(f)
    except FileNotFoundError:
        print(f"ERROR: File not found: {tasks_file}")
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"ERROR: Invalid JSON: {e}")
        sys.exit(1)

    # Run validation
    validator = AtomicityValidator(max_files=3, max_minutes=30)
    report = validator.validate_all(tasks)

    # Output report as JSON
    print(json.dumps(report, indent=2))

    # Exit with appropriate code
    sys.exit(0 if report['verdict'] == 'PASS' else 1)


# Entry point
if __name__ == '__main__':
    main()
